[package]
name = "simple-server"
version = "0.1.0"
authors = ["Smertelnyi Serhii <Serhii.Smertelnyi@bank.gov.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "1.3"
log = "0.4"
